import {ResourcePage,DetailPage,SettingsPage,resources} from './Workspace';
import {sessionUser,logout,hasSession,clearTokens,isOtpRateLimited} from './services/apiClient';
import { FormEvent, lazy, ReactNode, Suspense, useEffect, useRef, useState } from 'react';
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Bell, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, FileText, Hospital, LayoutDashboard, LogOut, Menu, Moon, Search, Settings, ShieldCheck, Stethoscope, Sun, Users, XCircle, type LucideIcon } from 'lucide-react';
import { motion } from 'framer-motion';
import { authService } from './services/authService';
import { adminDashboardService } from './services/adminDashboardService';
import { adminClinicService } from './services/adminClinicService';
import { adminDoctorService } from './services/adminDoctorService';
import { adminPatientService } from './services/adminPatientService';
import { adminAppointmentService } from './services/adminAppointmentService';
import { adminSpecialtyService } from './services/adminSpecialtyService';
import { adminServiceService } from './services/adminServiceService';
import { adminReviewService } from './services/adminReviewService';
import { adminNotificationService } from './services/adminNotificationService';
import { adminUserService } from './services/adminUserService';
import './modal.css';

const nav = [
  ['/', 'Dashboard', LayoutDashboard], ['clinics', 'Clinics', Hospital], ['doctors', 'Doctors', Stethoscope], ['owners', 'Clinic Owners', Building2], ['patients', 'Patients', Users], ['appointments', 'Appointments', CalendarDays], ['specialties', 'Specialties', FileText], ['services', 'Services', Building2], ['reviews', 'Reviews', CheckCircle2], ['notifications', 'Notifications', Bell], ['admin-users', 'Admin Users', ShieldCheck], ['analytics', 'Analytics', BarChart3], ['settings', 'Settings', Settings],
] as const;
const telegramBotUsername=(import.meta.env.VITE_TELEGRAM_BOT_USERNAME||'').trim().replace(/^@/,'');
const telegramBotUrl=telegramBotUsername?`https://t.me/${telegramBotUsername}`:'';
const normalizePhone=(value:string)=>{if(/[^\d+\s().-]/.test(value))return '';let digits=value.replace(/\D/g,'');if(digits.startsWith('00'))digits=digits.slice(2);if(digits.length===10&&digits.startsWith('0'))digits=digits.slice(1);if(digits.length===9)digits='998'+digits;return'+'+digits};

function Login() {
  const inFlight=useRef(false);
  const cache=useQueryClient(),navigate=useNavigate();
  const [phone,setPhone]=useState('+998'),[code,setCode]=useState(''),[step,setStep]=useState<'phone'|'code'>('phone'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0),[lastChannel,setLastChannel]=useState<'sms'|'telegram'>('sms');
  useEffect(()=>{if(cooldown<=0)return;const timer=window.setTimeout(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>window.clearTimeout(timer)},[cooldown]);
  async function send(channel:'sms'|'telegram'){
    if(inFlight.current||cooldown>0)return;
    setError('');
    const normalized=normalizePhone(phone);if(!/^\+[1-9]\d{7,14}$/.test(normalized)){setError('Telefon raqamini to‘g‘ri kiriting. Masalan: +998901234567');return}
    inFlight.current=true;setBusy(true);try{setPhone(normalized);await authService.requestOtp(normalized,channel);setLastChannel(channel);setCode('');setStep('code');setCooldown(60)}catch(e){const message=e instanceof Error?e.message:'Kodni yuborib bo‘lmadi.';setError(message);if(isOtpRateLimited(e))setCooldown(60)}finally{inFlight.current=false;setBusy(false)}
  }
  async function submit(event:FormEvent){event.preventDefault();if(inFlight.current)return;setError('');if(step==='phone'){await send('sms');return}if(!/^\d{6}$/.test(code)){setError('6 xonali tasdiqlash kodini kiriting.');return}inFlight.current=true;setBusy(true);setError('');try{await authService.verifyOtp(phone,code);await cache.invalidateQueries({queryKey:['admin-session']});navigate('/')}catch(e){setError(e instanceof Error?e.message:'Kod tasdiqlanmadi.')}finally{inFlight.current=false;setBusy(false)}}
  return <main className="login-page"><motion.form initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="login-card" onSubmit={submit}><div className="brand-mark"><ShieldCheck size={22}/></div><p className="eyebrow">DocNear operations</p><h1>Telefon orqali kirish</h1><p className="muted">Administrator uchun kirish kodi so‘raladi.</p><label>Telefon raqam<input type="tel" disabled={busy} readOnly={step==='code'} value={phone} onChange={e=>setPhone(e.target.value)} required autoComplete="tel" placeholder="+998901234567"/></label>{step==='code'&&<><label>Tasdiqlash kodi<input disabled={busy} autoComplete="one-time-code" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} onPaste={e=>{e.preventDefault();setCode(e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6))}} required/></label><p className="muted">Faqat oxirgi yuborilgan kod amal qiladi.</p></>}{error&&<div className="error-box"><CircleAlert size={16}/>{error}</div>}<button className="primary full" disabled={busy||(step==='phone'&&cooldown>0)}>{busy?'Kutilmoqda...':step==='phone'?'Tasdiqlash kodini yuborish':'Tasdiqlash'}</button>{step==='phone'&&<button type="button" className="full" disabled={busy||cooldown>0} onClick={()=>send('telegram')}>Kodni Telegram orqali olish</button>}{step==='phone'&&cooldown>0&&<p role="status">Qayta yuborish ({cooldown}s)</p>}{step==='phone'&&telegramBotUrl&&<a href={telegramBotUrl} target="_blank" rel="noreferrer">Telegram botni ochish</a>}{step==='code'&&<button type="button" className="full" disabled={busy||cooldown>0} onClick={()=>send(lastChannel)}>{cooldown>0?`Qayta yuborish (${cooldown}s)`:'Kodni qayta yuborish'}</button>}{step==='code'&&<button type="button" className="full" disabled={busy} onClick={()=>{setStep('phone');setCode('');setError('')}}>Telefon raqamini o‘zgartirish</button>}</motion.form></main>;
}

function Shell() { const cache=useQueryClient(); const current=cache.getQueryData<{role:string}>(['admin-session']); const location = useLocation(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const [dark, setDark] = useState(() => localStorage.getItem('docnear_admin_theme') === 'dark'); useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('docnear_admin_theme', dark ? 'dark' : 'light'); }, [dark]); useEffect(() => { const handler = () => navigate('/login'); window.addEventListener('admin-auth-expired', handler); return () => window.removeEventListener('admin-auth-expired', handler); }, [navigate]); return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="sidebar-brand"><span className="brand-mark"><ShieldCheck size={18} /></span><span>DocNear <b>Admin</b></span></div><nav>{nav.filter(([path])=>!['admin-users','settings'].includes(path)||current?.role==='super_admin').map(([path, label, Icon]) => <Link key={path} to={path} onClick={() => setOpen(false)} className={(path === '/' ? location.pathname === '/' : location.pathname.startsWith(`/${path}`)) ? 'active' : ''}><Icon size={17} /><span>{label}</span></Link>)}</nav><button className="logout" onClick={async () => { try { await logout(); } finally { cache.clear(); navigate('/login'); } }}><LogOut size={17} /> Sign out</button></aside><div className="content"><header><button className="icon-button mobile-only" onClick={() => setOpen(!open)} aria-label="Open navigation"><Menu size={20} /></button><div><p className="eyebrow">Control center</p><h2>{nav.find(([path]) => (path === '/' ? location.pathname === '/' : location.pathname.startsWith(`/${path}`)))?.[1] || 'Admin'}</h2></div><div className="header-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle dark mode">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><div className="avatar">A</div></div></header><section className="page"><Outlet /></section></div></div>; }

function Dashboard() { const query = useQuery({ queryKey: ['dashboard'], queryFn: adminDashboardService.dashboard }); if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState />; const data = query.data || {}; const cards: Array<[string, unknown, LucideIcon, string]> = [['Patients', data.total_patients, Users, 'teal'], ['Doctors', data.total_doctors, Stethoscope, 'blue'], ['Clinics', data.total_clinics, Hospital, 'amber'], ['Appointments', data.total_appointments, CalendarDays, 'rose']]; return <><div className="page-heading"><div><p className="eyebrow">Live platform overview</p><h1>Platform overview</h1></div><Link className="primary" to="/appointments"><CalendarDays size={16} /> Review appointments</Link></div><div className="metric-grid">{cards.map(([label, value, Icon, tone]) => <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="metric" key={label}><div className={`metric-icon ${tone}`}><Icon size={19} /></div><div><span>{label}</span><strong>{String(value ?? 0)}</strong></div></motion.div>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Attention queue</p><h3>Needs review</h3></div><Link to="/clinics">Open list <ChevronRight size={15} /></Link></div><div className="queue-list"><Queue icon={<ShieldCheck />} label="Clinic approvals" value={data.pending_clinic_approvals} /><Queue icon={<Stethoscope />} label="Doctor verifications" value={data.pending_doctor_verifications} /><Queue icon={<Clock3 />} label="Pending appointments" value={data.pending_count} /></div></div><div className="panel accent-panel"><p className="eyebrow">Backend status</p><h3>One source of truth</h3><p className="muted">All actions in this workspace write through Django REST APIs. Appointment state is never stored locally.</p><div className="status-line"><span className="status-dot" /> API integration ready</div></div></div></>; }
function Queue({ icon, label, value }: { icon: ReactNode; label: string; value: unknown }) { return <div className="queue-row"><span className="queue-icon">{icon}</span><span>{label}</span><strong>{String(value ?? 0)}</strong></div>; }
function Value({ value }: { value: unknown }) { if (typeof value === 'boolean') return value ? <span className="badge success"><CheckCircle2 size={13} />Yes</span> : <span className="badge muted-badge"><XCircle size={13} />No</span>; return <span>{value == null || value === '' ? '—' : String(value)}</span>; }
const Analytics = lazy(() => import('./AnalyticsPage'));
function Placeholder({ title }: { title: string }) { return <div className="panel empty-page"><Settings size={26} /><h3>{title}</h3><p className="muted">This protected view is connected to the backend service layer and ready for its next workflow form.</p></div>; }
function Loading() { return <div className="loading"><span className="spinner" /> Loading live data...</div>; }
function ErrorState() { return <div className="panel error-state"><CircleAlert size={22} /><h3>Unable to load this view</h3><p className="muted">Check the API URL and administrator permissions, then try again.</p></div>; }
function EmptyState() { return <div className="empty-state"><FileText size={24} /><h3>No records found</h3><p className="muted">Try changing the search or wait for backend data.</p></div>; }
function Protected() { const q=useQuery({queryKey:['admin-session'],queryFn:sessionUser,enabled:hasSession(),retry:false});if(!hasSession())return <Navigate to="/login" replace/>;if(q.isLoading)return <Loading/>;if(q.isError||!['admin','super_admin'].includes(q.data?.role||'')){clearTokens();return <Navigate to="/login" replace/>}return <Outlet/>; }
export default function App() { return <Routes><Route path="/login" element={<Login />} /><Route element={<Protected />}><Route element={<Shell />}><Route index element={<Dashboard />} /><Route path="analytics" element={<Suspense fallback={<Loading />}><Analytics /></Suspense>} /><Route path="settings" element={<SettingsPage />} />{Object.keys(resources).map(type => <Route key={type} path={type} element={<ResourcePage type={type} />} />)}{Object.keys(resources).map(type => <Route key={`${type}-detail`} path={`${type}/:id`} element={<DetailPage type={type} />} />)}</Route></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
