# Generated by Django 5.2.17 on 2026-09-06 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_created', 'booking created'), ('booking_confirmed', 'booking confirmed'), ('booking_cancelled', 'booking cancelled'), ('booking_rescheduled', 'booking rescheduled'), ('booking_updated', 'booking updated'), ('appointment_reminder', 'appointment reminder'), ('doctor_schedule_changed', 'doctor schedule changed'), ('doctor_verification', 'doctor verification'), ('clinic_verification', 'clinic verification'), ('system_message', 'system message'), ('general', 'general')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=50)),
                ('deduplication_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
