# Generated by Django 5.2.17 on 2026-09-06 12:47

import apps.appointments.models
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(default=apps.appointments.models.booking_id, editable=False, max_length=32, unique=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reserved_until', models.DateTimeField()),
                ('patient_note', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waiting', 'Waiting'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('no_show', 'No show')], db_index=True, default='pending', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialties.specialty')),
            ],
            options={
                'ordering': ['-appointment_date', '-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appointments.appointment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'appointment_date'], name='appointment_clinic__843526_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__lte', models.F('reserved_until')), ('starts_at__lt', models.F('ends_at'))), name='valid_appointment_interval'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('pending', 'confirmed', 'waiting', 'in_progress', 'completed', 'no_show'))), expressions=[('doctor', '='), (models.Func('starts_at', 'reserved_until', models.Value('[)'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='exclude_doctor_overlapping_reservations'),
        ),
    ]
