# Generated by Django 5.2.17 on 2026-09-07 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_date', models.DateField()),
                ('time_range', models.CharField(choices=[('any', 'any'), ('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening')], default='any', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('cancelled', 'cancelled'), ('booked', 'booked')], default='waiting', max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('patient', 'doctor', 'clinic', 'preferred_date', 'time_range'), name='unique_active_waitlist')],
            },
        ),
    ]
