import React, { useEffect, useState } from 'react';
import { AlertCircle, Bot, Phone, ShieldCheck, X } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useOtpCooldown } from '../../hooks/useOtpCooldown';
import { normalizeUzPhone, validE164Phone } from '../../utils/phone';

const telegramBotUsername = (import.meta.env.VITE_TELEGRAM_BOT_USERNAME || '').trim().replace(/^@/, '');
const telegramBotUrl = telegramBotUsername ? `https://t.me/${telegramBotUsername}` : '';

export const AuthModal: React.FC<{isOpen?: boolean; onClose?: () => void; initialMode?: 'login'|'register'; onSuccess?: () => void}> = ({isOpen: openProp,onClose: closeProp,initialMode,onSuccess}) => {
  const auth=useAuth(); const open=openProp ?? auth.isAuthModalOpen; const close=closeProp ?? auth.closeAuthModal;
  const [purpose,setPurpose]=useState<'login'|'register'>(initialMode ?? auth.authModalMode); const [phone,setPhone]=useState('+998'); const [code,setCode]=useState(''); const [step,setStep]=useState<'phone'|'code'>('phone'); const [firstName,setFirstName]=useState(''); const [lastName,setLastName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [lastChannel,setLastChannel]=useState<'sms'|'telegram'>('sms'); const cooldown=useOtpCooldown();
  useEffect(()=>{if(open){setPurpose(initialMode ?? auth.authModalMode);setStep('phone');setError('');setCode('')}},[open,initialMode,auth.authModalMode]);
  if(!open)return null;
  async function send(channel:'sms'|'telegram'){setError('');const normalized=normalizeUzPhone(phone);if(!validE164Phone(normalized)){setError('Telefon raqamini to‘g‘ri kiriting. Masalan: +998901234567');return}if(purpose==='register'&&!firstName.trim()){setError('Ismingizni kiriting.');return}setBusy(true);try{setPhone(normalized);await auth.requestOtp({phone:normalized,purpose,channel,firstName,lastName});setLastChannel(channel);setStep('code');cooldown.start()}catch(e){const message=e instanceof Error?e.message:'Kodni yuborib bo‘lmadi.';setError(message);if(message.includes('biroz kuting'))cooldown.start()}finally{setBusy(false)}}
  async function verify(){setError('');if(!/^\d{6}$/.test(code)){setError('6 xonali tasdiqlash kodini kiriting.');return}setBusy(true);try{await auth.verifyOtp({phone,code,purpose});onSuccess?.();close();auth.closeAuthModal()}catch(e){setError(e instanceof Error?e.message:'Kod tasdiqlanmadi.')}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-50 bg-slate-950/50 flex items-center justify-center p-4"><div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-3xl p-6 space-y-4 relative"><button aria-label="Yopish" onClick={close} className="absolute right-4 top-4"><X/></button><h2 className="text-xl font-bold">{purpose==='login'?'Telefon orqali kirish':'Hisob yaratish'}</h2><p className="text-sm text-slate-500">{purpose==='login'?'Kirish kodi so‘raladi.':'Ro‘yxatdan o‘tish kodi so‘raladi.'} Email va parol talab qilinmaydi.</p>{error&&<div className="text-rose-700 flex gap-2"><AlertCircle size={18}/>{error}</div>}{step==='phone'?<div className="space-y-3">{purpose==='register'&&<div className="grid grid-cols-2 gap-2"><input className="border rounded-xl p-3" placeholder="Ism" value={firstName} onChange={e=>setFirstName(e.target.value)}/><input className="border rounded-xl p-3" placeholder="Familiya" value={lastName} onChange={e=>setLastName(e.target.value)}/></div>}<input className="w-full border rounded-xl p-3" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+998901234567"/><button disabled={busy} onClick={()=>send('sms')} className="w-full bg-blue-600 text-white p-3 rounded-xl flex justify-center gap-2"><Phone size={18}/>Tasdiqlash kodini yuborish</button><button disabled={busy} onClick={()=>send('telegram')} className="w-full border p-3 rounded-xl flex justify-center gap-2"><Bot size={18}/>Kodni Telegram orqali olish</button>{telegramBotUrl&&<a href={telegramBotUrl} target="_blank" rel="noreferrer" className="block text-center text-sm text-blue-600">Telegram botni ochish</a>}</div>:<div className="space-y-3"><input className="w-full border rounded-xl p-3 text-center tracking-[.4em]" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><p className="text-xs text-slate-500 text-center">Faqat oxirgi yuborilgan kod amal qiladi.</p><button disabled={busy} onClick={verify} className="w-full bg-blue-600 text-white p-3 rounded-xl flex justify-center gap-2"><ShieldCheck size={18}/>Tasdiqlash</button><button disabled={busy||cooldown.seconds>0} onClick={()=>send(lastChannel)} className="w-full text-blue-600">{cooldown.seconds>0?`Qayta yuborish (${cooldown.seconds}s)`:'Kodni qayta yuborish'}</button></div>}<button onClick={()=>{setPurpose(purpose==='login'?'register':'login');setStep('phone')}} className="w-full text-sm text-blue-600">{purpose==='login'?'Ro‘yxatdan o‘tish':'Kirish'}</button></div></div>;
};
