import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Activity, AlertCircle, Bot, Phone, ShieldCheck } from 'lucide-react';
import { useAuthStore } from '../../store/useAuthStore';

export const LoginPage: React.FC = () => {
  const [phone,setPhone]=useState('+998'),[code,setCode]=useState(''),[step,setStep]=useState<'phone'|'code'>('phone'),[error,setError]=useState('');
  const {requestOtp,verifyOtp,isLoading}=useAuthStore(); const navigate=useNavigate();
  async function send(channel:'sms'|'telegram') {setError('');if(!/^\+[1-9]\d{7,14}$/.test(phone)){setError('Telefon raqamni xalqaro formatda kiriting: +998901234567');return}if(await requestOtp(phone,channel))setStep('code');else setError('Tasdiqlash kodini yuborib bo‘lmadi.');}
  async function submit(e:React.FormEvent){e.preventDefault();if(step==='phone'){await send('sms');return}if(!/^\d{6}$/.test(code)){setError('6 xonali tasdiqlash kodini kiriting.');return}if(await verifyOtp({phoneNumber:phone,code}))navigate('/dashboard');else setError('Tasdiqlash kodi noto‘g‘ri yoki muddati tugagan.');}
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center p-4"><form onSubmit={submit} className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8 space-y-5 shadow-sm"><div className="flex items-center gap-3"><span className="p-2 bg-blue-600 text-white rounded-xl"><Activity/></span><div><h1 className="text-2xl font-bold">DocNear Doctor</h1><p className="text-sm text-slate-500">Telefon orqali xavfsiz kirish</p></div></div><p className="text-sm text-slate-500">Email va parol talab qilinmaydi.</p>{error&&<div className="p-3 bg-rose-50 text-rose-700 rounded-xl flex gap-2"><AlertCircle size={18}/>{error}</div>}<label className="block text-sm font-semibold">Telefon raqam<input className="mt-1 w-full border rounded-xl p-3 dark:bg-slate-800" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+998901234567" required/></label>{step==='code'&&<label className="block text-sm font-semibold">Tasdiqlash kodi<input className="mt-1 w-full border rounded-xl p-3 text-center tracking-[.4em] dark:bg-slate-800" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/></label>}<button disabled={isLoading} className="w-full bg-blue-600 text-white rounded-xl p-3 font-semibold flex justify-center gap-2">{step==='phone'?<Phone size={18}/>:<ShieldCheck size={18}/>} {isLoading?'Kutilmoqda...':step==='phone'?'Tasdiqlash kodini yuborish':'Tasdiqlash'}</button>{step==='phone'&&<button type="button" disabled={isLoading} onClick={()=>send('telegram')} className="w-full border rounded-xl p-3 flex justify-center gap-2"><Bot size={18}/>Kodni Telegram orqali olish</button>}{step==='code'&&<button type="button" disabled={isLoading} onClick={()=>send('sms')} className="w-full text-blue-600">Kodni qayta yuborish</button>}</form></div>;
};
