# Generated by Django 5.2.17 on 2026-09-11 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use an international phone number, e.g. +998901234567.')])),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('verify_phone', 'Verify phone'), ('reset', 'Reset')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('telegram', 'Telegram')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'created_at'], name='accounts_ot_phone_purpose_idx')],
            },
        ),
    ]
