import {ResourcePage,DetailPage,SettingsPage,resources} from './Workspace';
import {sessionUser,logout,hasSession,clearTokens} from './services/apiClient';
import { FormEvent, lazy, ReactNode, Suspense, useEffect, useState } from 'react';
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Bell, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, FileText, Hospital, LayoutDashboard, LogOut, Menu, Moon, Search, Settings, ShieldCheck, Stethoscope, Sun, Users, XCircle, type LucideIcon } from 'lucide-react';
import { motion } from 'framer-motion';
import { authService } from './services/authService';
import { adminDashboardService } from './services/adminDashboardService';
import { adminClinicService } from './services/adminClinicService';
import { adminDoctorService } from './services/adminDoctorService';
import { adminPatientService } from './services/adminPatientService';
import { adminAppointmentService } from './services/adminAppointmentService';
import { adminSpecialtyService } from './services/adminSpecialtyService';
import { adminServiceService } from './services/adminServiceService';
import { adminReviewService } from './services/adminReviewService';
import { adminNotificationService } from './services/adminNotificationService';
import { adminUserService } from './services/adminUserService';
import './modal.css';

const nav = [
  ['/', 'Dashboard', LayoutDashboard], ['clinics', 'Clinics', Hospital], ['doctors', 'Doctors', Stethoscope], ['owners', 'Clinic Owners', Building2], ['patients', 'Patients', Users], ['appointments', 'Appointments', CalendarDays], ['specialties', 'Specialties', FileText], ['services', 'Services', Building2], ['reviews', 'Reviews', CheckCircle2], ['notifications', 'Notifications', Bell], ['admin-users', 'Admin Users', ShieldCheck], ['analytics', 'Analytics', BarChart3], ['settings', 'Settings', Settings],
] as const;

function Login() { const cache=useQueryClient(); const navigate = useNavigate(); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await authService.login(identifier, password); await cache.invalidateQueries({queryKey:['admin-session']}); navigate('/'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to sign in.'); } finally { setBusy(false); } }; return <main className="login-page"><motion.form initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="login-card" onSubmit={submit}><div className="brand-mark"><ShieldCheck size={22} /></div><p className="eyebrow">DocNear operations</p><h1>Admin sign in</h1><p className="muted">Use an administrator account to manage the shared backend.</p><label>Identifier<input value={identifier} onChange={e => setIdentifier(e.target.value)} required autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required autoComplete="current-password" /></label>{error && <div className="error-box"><CircleAlert size={16} />{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'}</button></motion.form></main>; }

function Shell() { const cache=useQueryClient(); const current=cache.getQueryData<{role:string}>(['admin-session']); const location = useLocation(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const [dark, setDark] = useState(() => localStorage.getItem('docnear_admin_theme') === 'dark'); useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('docnear_admin_theme', dark ? 'dark' : 'light'); }, [dark]); useEffect(() => { const handler = () => navigate('/login'); window.addEventListener('admin-auth-expired', handler); return () => window.removeEventListener('admin-auth-expired', handler); }, [navigate]); return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="sidebar-brand"><span className="brand-mark"><ShieldCheck size={18} /></span><span>DocNear <b>Admin</b></span></div><nav>{nav.filter(([path])=>!['admin-users','settings'].includes(path)||current?.role==='super_admin').map(([path, label, Icon]) => <Link key={path} to={path} onClick={() => setOpen(false)} className={(path === '/' ? location.pathname === '/' : location.pathname.startsWith(`/${path}`)) ? 'active' : ''}><Icon size={17} /><span>{label}</span></Link>)}</nav><button className="logout" onClick={async () => { try { await logout(); } finally { cache.clear(); navigate('/login'); } }}><LogOut size={17} /> Sign out</button></aside><div className="content"><header><button className="icon-button mobile-only" onClick={() => setOpen(!open)} aria-label="Open navigation"><Menu size={20} /></button><div><p className="eyebrow">Control center</p><h2>{nav.find(([path]) => (path === '/' ? location.pathname === '/' : location.pathname.startsWith(`/${path}`)))?.[1] || 'Admin'}</h2></div><div className="header-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle dark mode">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><div className="avatar">A</div></div></header><section className="page"><Outlet /></section></div></div>; }

function Dashboard() { const query = useQuery({ queryKey: ['dashboard'], queryFn: adminDashboardService.dashboard }); if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState />; const data = query.data || {}; const cards: Array<[string, unknown, LucideIcon, string]> = [['Patients', data.total_patients, Users, 'teal'], ['Doctors', data.total_doctors, Stethoscope, 'blue'], ['Clinics', data.total_clinics, Hospital, 'amber'], ['Appointments', data.total_appointments, CalendarDays, 'rose']]; return <><div className="page-heading"><div><p className="eyebrow">Live platform overview</p><h1>Platform overview</h1></div><Link className="primary" to="/appointments"><CalendarDays size={16} /> Review appointments</Link></div><div className="metric-grid">{cards.map(([label, value, Icon, tone]) => <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="metric" key={label}><div className={`metric-icon ${tone}`}><Icon size={19} /></div><div><span>{label}</span><strong>{String(value ?? 0)}</strong></div></motion.div>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Attention queue</p><h3>Needs review</h3></div><Link to="/clinics">Open list <ChevronRight size={15} /></Link></div><div className="queue-list"><Queue icon={<ShieldCheck />} label="Clinic approvals" value={data.pending_clinic_approvals} /><Queue icon={<Stethoscope />} label="Doctor verifications" value={data.pending_doctor_verifications} /><Queue icon={<Clock3 />} label="Pending appointments" value={data.pending_count} /></div></div><div className="panel accent-panel"><p className="eyebrow">Backend status</p><h3>One source of truth</h3><p className="muted">All actions in this workspace write through Django REST APIs. Appointment state is never stored locally.</p><div className="status-line"><span className="status-dot" /> API integration ready</div></div></div></>; }
function Queue({ icon, label, value }: { icon: ReactNode; label: string; value: unknown }) { return <div className="queue-row"><span className="queue-icon">{icon}</span><span>{label}</span><strong>{String(value ?? 0)}</strong></div>; }
function Value({ value }: { value: unknown }) { if (typeof value === 'boolean') return value ? <span className="badge success"><CheckCircle2 size={13} />Yes</span> : <span className="badge muted-badge"><XCircle size={13} />No</span>; return <span>{value == null || value === '' ? '—' : String(value)}</span>; }
const Analytics = lazy(() => import('./AnalyticsPage'));
function Placeholder({ title }: { title: string }) { return <div className="panel empty-page"><Settings size={26} /><h3>{title}</h3><p className="muted">This protected view is connected to the backend service layer and ready for its next workflow form.</p></div>; }
function Loading() { return <div className="loading"><span className="spinner" /> Loading live data...</div>; }
function ErrorState() { return <div className="panel error-state"><CircleAlert size={22} /><h3>Unable to load this view</h3><p className="muted">Check the API URL and administrator permissions, then try again.</p></div>; }
function EmptyState() { return <div className="empty-state"><FileText size={24} /><h3>No records found</h3><p className="muted">Try changing the search or wait for backend data.</p></div>; }
function Protected() { const q=useQuery({queryKey:['admin-session'],queryFn:sessionUser,enabled:hasSession(),retry:false});if(!hasSession())return <Navigate to="/login" replace/>;if(q.isLoading)return <Loading/>;if(q.isError||!['admin','super_admin'].includes(q.data?.role||'')){clearTokens();return <Navigate to="/login" replace/>}return <Outlet/>; }
export default function App() { return <Routes><Route path="/login" element={<Login />} /><Route element={<Protected />}><Route element={<Shell />}><Route index element={<Dashboard />} /><Route path="analytics" element={<Suspense fallback={<Loading />}><Analytics /></Suspense>} /><Route path="settings" element={<SettingsPage />} />{Object.keys(resources).map(type => <Route key={type} path={type} element={<ResourcePage type={type} />} />)}{Object.keys(resources).map(type => <Route key={`${type}-detail`} path={`${type}/:id`} element={<DetailPage type={type} />} />)}</Route></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
