# Generated by Django 5.2.17 on 2026-09-06 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='doctors/%Y/%m/')),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('education', models.TextField(blank=True)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('pending_profile', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0, editable=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_bookings', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('consultation_duration', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('buffer_time', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)])),
                ('max_appointments_per_day', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_affiliations', to='clinics.clinic')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialties.specialty')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'clinic'), name='unique_doctor_clinic'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('doctor',), name='one_primary_clinic'), models.CheckConstraint(condition=models.Q(('buffer_time__lte', 120), ('consultation_duration__gte', 5), ('consultation_duration__lte', 240), ('max_appointments_per_day__gte', 1)), name='valid_booking_policy')],
            },
        ),
    ]
