import React, { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Activity, AlertCircle, Bot, Phone, ShieldCheck } from 'lucide-react';
import { isOtpRateLimited } from '../../services/apiClient';
import { useAuthStore } from '../../store/useAuthStore';

const telegramBotUsername=(import.meta.env.VITE_TELEGRAM_BOT_USERNAME||'').trim().replace(/^@/,'');
const telegramBotUrl=telegramBotUsername?`https://t.me/${telegramBotUsername}`:'';
const normalizePhone=(value:string)=>{if(/[^\d+\s().-]/.test(value))return '';let digits=value.replace(/\D/g,'');if(digits.startsWith('00'))digits=digits.slice(2);if(digits.length===10&&digits.startsWith('0'))digits=digits.slice(1);if(digits.length===9)digits='998'+digits;return'+'+digits};

export const LoginPage: React.FC = () => {
  const [phone,setPhone]=useState('+998'),[code,setCode]=useState(''),[step,setStep]=useState<'phone'|'code'>('phone'),[error,setError]=useState(''),[cooldown,setCooldown]=useState(0),[lastChannel,setLastChannel]=useState<'sms'|'telegram'>('sms');
  const inFlight=useRef(false);
  const {requestOtp,verifyOtp,isLoading}=useAuthStore(); const navigate=useNavigate();
  useEffect(()=>{if(cooldown<=0)return;const timer=window.setTimeout(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>window.clearTimeout(timer)},[cooldown]);
  async function send(channel:'sms'|'telegram') {if(inFlight.current||isLoading||cooldown>0)return;setError('');const normalized=normalizePhone(phone);if(!/^\+[1-9]\d{7,14}$/.test(normalized)){setError('Telefon raqamini to‘g‘ri kiriting. Masalan: +998901234567');return}inFlight.current=true;try{setPhone(normalized);await requestOtp(normalized,channel);setLastChannel(channel);setCode('');setStep('code');setCooldown(60)}catch(error){const message=error instanceof Error?error.message:'Tasdiqlash kodini yuborib bo‘lmadi.';setError(message);if(isOtpRateLimited(error))setCooldown(60)}finally{inFlight.current=false}}
  async function submit(e:React.FormEvent){e.preventDefault();if(inFlight.current||isLoading)return;setError('');if(step==='phone'){await send('sms');return}if(!/^\d{6}$/.test(code)){setError('6 xonali tasdiqlash kodini kiriting.');return}inFlight.current=true;try{if(await verifyOtp({phoneNumber:phone,code}))navigate('/dashboard');else setError(useAuthStore.getState().error||'Tasdiqlash kodi noto‘g‘ri yoki muddati tugagan.')}finally{inFlight.current=false}}
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center p-4"><form onSubmit={submit} className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8 space-y-5 shadow-sm"><div className="flex items-center gap-3"><span className="p-2 bg-blue-600 text-white rounded-xl"><Activity/></span><div><h1 className="text-2xl font-bold">DocNear Doctor</h1><p className="text-sm text-slate-500">Telefon orqali xavfsiz kirish</p></div></div><p className="text-sm text-slate-500">Kirish kodi so‘raladi. Email va parol talab qilinmaydi.</p>{error&&<div className="p-3 bg-rose-50 text-rose-700 rounded-xl flex gap-2"><AlertCircle size={18}/>{error}</div>}<label className="block text-sm font-semibold">Telefon raqam<input disabled={isLoading} className="mt-1 w-full border rounded-xl p-3 dark:bg-slate-800" type="tel" autoComplete="tel" readOnly={step==='code'} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+998901234567" required/></label>{step==='code'&&<><label className="block text-sm font-semibold">Tasdiqlash kodi<input disabled={isLoading} className="mt-1 w-full border rounded-xl p-3 text-center tracking-[.4em] dark:bg-slate-800" autoComplete="one-time-code" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} onPaste={e=>{e.preventDefault();setCode(e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6))}} required/></label><p className="text-xs text-slate-500 text-center">Faqat oxirgi yuborilgan kod amal qiladi.</p></>}<button disabled={isLoading||(step==='phone'&&cooldown>0)} className="w-full bg-blue-600 text-white rounded-xl p-3 font-semibold flex justify-center gap-2">{step==='phone'?<Phone size={18}/>:<ShieldCheck size={18}/>} {isLoading?'Kutilmoqda...':step==='phone'?'Tasdiqlash kodini yuborish':'Tasdiqlash'}</button>{step==='phone'&&<button type="button" disabled={isLoading||cooldown>0} onClick={()=>send('telegram')} className="w-full border rounded-xl p-3 flex justify-center gap-2"><Bot size={18}/>Kodni Telegram orqali olish</button>}{step==='phone'&&cooldown>0&&<p role="status" className="text-sm text-center">Qayta yuborish ({cooldown}s)</p>}{step==='phone'&&telegramBotUrl&&<a href={telegramBotUrl} target="_blank" rel="noreferrer" className="block text-center text-sm text-blue-600">Telegram botni ochish</a>}{step==='code'&&<button type="button" disabled={isLoading||cooldown>0} onClick={()=>send(lastChannel)} className="w-full text-blue-600">{cooldown>0?`Qayta yuborish (${cooldown}s)`:'Kodni qayta yuborish'}</button>}{step==='code'&&<button type="button" disabled={isLoading} onClick={()=>{setStep('phone');setCode('');setError('')}} className="w-full text-sm text-blue-600">Telefon raqamini o‘zgartirish</button>}</form></div>;
};
